version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      day: "monday"
    commit-message:
      prefix: "Deps"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    groups:
      go-modules:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      day: "monday"
    commit-message:
      prefix: "Deps"
    groups:
      github-actions:
        patterns:
          - "*"
