version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    groups:
      dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
