version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
