// SPDX-FileCopyrightText: 2023-2024 Greenbone AG
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package keycloak_client_golang

// THIS IS AN AUTOGENERATED FILE. DO NOT TOUCH!

var Version = "0.2.3"
