// SPDX-FileCopyrightText: 2023 Greenbone AG
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Copyright (C) Greenbone Networks GmbH
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package keycloak_client_golang

// THIS IS AN AUTOGENERATED FILE. DO NOT TOUCH!

var Version = "0.2.2-dev1"
